"use client";

import React, { useState, useEffect } from 'react';
import BlogsHeroSection from '@/components/blogs/BlogsHeroSection';
import CTASection from '@/components/seo/CTASection';
import Link from 'next/link';
import Image from 'next/image';

interface BlogPost {
    title: string;
    slug: string;
    thumbnail: string;
    date: string;
    excerpt?: string;
}

export default function BlogsPage() {
    const [blogs, setBlogs] = useState<BlogPost[]>([]);
    const [displayedBlogs, setDisplayedBlogs] = useState<BlogPost[]>([]);
    const [page, setPage] = useState(1);
    const [isLoading, setIsLoading] = useState(true);
    const perPage = 9;

    useEffect(() => {
        // Fetch static JSON generated by import script
        fetch('/_next/data/blogs.json') // We will copy it to public or import it directly. Actually, Next.js can import it statically.
            .then(res => res.json())
            .catch(() => {
                // Fallback direct import for client side
                import('@/data/blogs.json').then(module => setBlogs(module.default || [])).catch(() => setBlogs([]));
            })
            .finally(() => setIsLoading(false));
            
        import('@/data/blogs.json')
            .then(module => {
                const data = module.default || module;
                setBlogs(data);
                setDisplayedBlogs(data.slice(0, perPage));
                setIsLoading(false);
            })
            .catch(() => setIsLoading(false));
    }, []);

    const loadMore = () => {
        const nextTarget = (page + 1) * perPage;
        setDisplayedBlogs(blogs.slice(0, nextTarget));
        setPage(page + 1);
    };

    const hasMore = displayedBlogs.length < blogs.length;

    return (
        <div className="flex flex-col min-h-screen bg-white dark:bg-gray-900 font-['Poppins',sans-serif]">
            <main className="flex-1">
                <BlogsHeroSection />
                
                <section className="py-20 px-4 bg-[#f9fafa]">
                    <div className="max-w-[1200px] mx-auto">
                        
                        {isLoading ? (
                            <div className="flex justify-center my-20">
                                <div className="w-10 h-10 border-4 border-gray-200 border-t-[#3AAB43] rounded-full animate-spin"></div>
                            </div>
                        ) : blogs.length === 0 ? (
                            <div className="text-center text-red-600 bg-red-50 py-4 px-6 rounded-lg my-10 border border-red-100 shadow-sm max-w-md mx-auto">
                                No blog posts found. Run the import script.
                            </div>
                        ) : (
                            <>
                                {/* Blog Grid matching exact CSS mapping */}
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[30px] mb-[40px]">
                                    {displayedBlogs.map((blog, idx) => (
                                        <div key={idx} className="bg-white rounded-[12px] shadow-[0_4px_15px_rgba(0,0,0,0.08)] overflow-hidden transition-all duration-300 hover:-translate-y-[5px] hover:shadow-[0_8px_25px_rgba(0,0,0,0.12)] flex flex-col border border-[#eaeaea]">
                                            <div className="relative w-full h-[200px] overflow-hidden bg-gray-100">
                                                <Image 
                                                    src={blog.thumbnail || '/images/hero-bg.jpg'} 
                                                    alt={blog.title} 
                                                    fill 
                                                    className="object-cover"
                                                />
                                            </div>
                                            <div className="p-[25px] flex-grow flex flex-col">
                                                <h3 className="text-[#1E3A1A] text-[1.25rem] font-bold mb-[15px] leading-[1.4] line-clamp-2">
                                                    {blog.title}
                                                </h3>
                                                <p className="text-[#555] text-[0.95rem] leading-[1.6] mb-[20px] flex-grow line-clamp-3">
                                                    {blog.excerpt || `Discover more about ${blog.title.toLowerCase()} and how it impacts your strategy and growth.`}
                                                </p>
                                                <Link 
                                                    href={`/blogs/${blog.slug}`} 
                                                    className="self-start inline-block bg-[#3AAB43] text-white px-[20px] py-[10px] rounded-[5px] font-semibold text-[0.9rem] transition-colors hover:bg-[#2b8432]"
                                                >
                                                    Read More
                                                </Link>
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                {/* Load More Button */}
                                {hasMore && (
                                    <div className="text-center mt-10 mb-5">
                                        <button 
                                            onClick={loadMore} 
                                            className="bg-[#FED52B] text-[#1E3A1A] border-none px-10 py-3.5 text-base font-bold rounded-full cursor-pointer transition-all duration-200 shadow-[0_4px_10px_rgba(0,0,0,0.1)] hover:scale-105 hover:shadow-[0_6px_15px_rgba(0,0,0,0.15)] focus:outline-none"
                                        >
                                            Load More Articles
                                        </button>
                                    </div>
                                )}
                            </>
                        )}
                    </div>
                </section>
                
                <CTASection />
            </main>
        </div>
    );
}
